name: "Run Tests"

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  run-tests:
    runs-on: "ubuntu-24.04"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: Set up Docker Buildx
        uses: "docker/setup-buildx-action@v1"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.2"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress"

      - name: "Install laravel"
        run: "composer global require laravel/installer:dev-master"

      - shell: 'script -q -e -c "bash {0}"'
        run: "./caprover-laravel new project1 project1 --no-interaction --migratoro"

      - run: "cd project1 && docker compose up -d && sleep 5"

      - run: "cd project1 && sudo chown 32767:32767 -R ."
      - run: "cd project1 && sudo chown 1001:118 resources/views/welcome.blade.php"
      - run: "cd project1 && sudo chown 1001:118 database/schema.txt"

      - run: "cd project1 && docker compose exec php-nginx php artisan migrate"

#      - name: Setup upterm session
#        uses: "lhotari/action-upterm@v1"

      - run: |
          echo '<?php echo App\Models\User::count(); ?> users' > project1/resources/views/welcome.blade.php;

      - run: "curl -s 127.0.0.1:8081"

      - run: "(curl -s 127.0.0.1:8081 | grep '0 users') || false"

      # Test migrator

      - run: |
          echo -e 'Thing\n    name: string\n' > project1/database/schema.txt;

      - run: "cd project1 && docker compose exec php-nginx php artisan migrator"

      - run: |
          echo '<?php App\Models\Thing::create(); echo App\Models\Thing::count(); ?> thing' > project1/resources/views/welcome.blade.php;

      - run: "(curl -s 127.0.0.1:8081 | grep '1 thing') || false"

      - run: "(curl -s 127.0.0.1:8081 | grep '2 thing') || false"
